# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pEDKjCIzeKiiyzmX2hB8C7BepwcMmLMk
"""

x = float(input("type a number: "))
y = float(input("type another number: "))
proc = input("what process (+, -, *, /): ")

if proc == "+":
    print(x + y)
elif proc == "-":
    print(x - y)
elif proc == "*":
    print(x * y)
elif proc == "/":
    print(x / y)
else:
    print("invalid operator")