# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15FokGsQSzWk3ym4pbD4R1_fEF6s_ylAo
"""



print ("hello world")