# -*- coding: utf-8 -*-
"""simple ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IA3BdFsJb2pRgTaRvUOJ2jAAsLItrPUp
"""

def chatbot_response(user_input):
    user_input = user_input.lower()

    if "hello" in user_input or "hi" in user_input:
        return "Hello there! How can I help you today?"
    elif "how are you" in user_input:
        return "I am a chatbot, so I don't have feelings, but I'm ready to assist you!"
    elif "what is your name" in user_input:
        return "I am a simple rule-based chatbot."
    elif "quit" in user_input or "exit" in user_input or "bye" in user_input:
        return "Goodbye! Have a great day!"
    else:
        return "I'm sorry, I don't understand that. Can you please rephrase?"

print("Simple Chatbot: Hello! Type 'quit' or 'exit' to end the conversation.")

while True:
    user_input = input("You: ")
    response = chatbot_response(user_input)
    print(f"Simple Chatbot: {response}")

    if "quit" in user_input.lower() or "exit" in user_input.lower() or "bye" in user_input.lower():
        break